//! gir GLib-2.0
//! gir GModule-2.0
//! gir GObject-2.0
//! gir Gio-2.0
//! gir cairo-1.0
//! gir HarfBuzz-0.0
//! gir Pango-1.0
//! gir PangoCairo-1.0
//! gir GdkPixbuf-2.0
//! gir Gdk-4.0
//! gir Gtk-4.0
//! info name "gtk4"
//! info description "GTK 4 D language bindings"
//! info license "LGPL"
//! info authors "Generated by gidgen"

// GTK 4 綁定定義，包含完整的依賴鏈
// GLib-2.0: 基礎庫
// GModule-2.0: 模組系統
// GObject-2.0: 對象系統
// Gio-2.0: I/O 庫
// cairo-1.0: 2D 圖形庫
// Pango-1.0: 文字渲染
// PangoCairo-1.0: Pango + Cairo 整合
// GdkPixbuf-2.0: 圖像處理
// Gdk-4.0: 繪圖工具包
// Gtk-4.0: 主要 GUI 工具包
