#!/bin/bash

echo "正在準備 GTK 4 D 語言綁定生成..."

# 檢查必要工具
if ! command -v pkg-config &> /dev/null; then
    echo "錯誤：pkg-config 未安裝"
    echo "請運行：brew install pkg-config"
    exit 1
fi

# 檢查 GTK 4 安裝
echo "檢查 GTK 4 安裝..."
if pkg-config --exists gtk4; then
    echo "✅ GTK 4 已安裝"
    echo "GTK 4 版本：$(pkg-config --modversion gtk4)"
else
    echo "❌ GTK 4 未找到"
    echo "請確保 GTK 4 已正確安裝"
    exit 1
fi

# 檢查 GIR 文件
echo "檢查 GIR 文件..."
GTK4_GIR_PATH="/usr/local/share/gir-1.0/Gtk-4.0.gir"
if [ -f "$GTK4_GIR_PATH" ]; then
    echo "✅ 找到 GTK 4 GIR 文件：$GTK4_GIR_PATH"
else
    echo "❌ 未找到 GTK 4 GIR 文件"
    echo "請檢查 GTK 4 開發包是否已安裝"
    exit 1
fi

# 檢查 gidgen
echo "檢查 gidgen..."
if dub list | grep -q gidgen; then
    echo "✅ gidgen 已安裝"
else
    echo "正在安裝 gidgen..."
    dub fetch gidgen
fi

# 創建綁定定義目錄
mkdir -p bindings/definitions
mkdir -p bindings/output

# 創建基本的 GTK 4 綁定定義文件
cat > bindings/definitions/gtk4.d << 'EOF'
//! gir Gtk-4.0
//! info name "gtk4"
//! info description "GTK 4 D language bindings"
//! info license "LGPL"
//! info authors "Generated by gidgen"

// 基本的 GTK 4 綁定定義
// 可以根據需要添加更多自定義配置
EOF

echo "✅ 綁定定義文件已創建"

# 生成綁定（如果 gidgen 可用）
echo "嘗試生成 GTK 4 綁定..."
echo "注意：這可能需要一些時間..."

# 檢查是否可以運行 gidgen
if dub run gidgen -- --help > /dev/null 2>&1; then
    echo "正在生成 GTK 4 綁定..."
    dub run gidgen -- \
        --defs bindings/definitions \
        --gir-path /usr/local/share/gir-1.0 \
        --pkg-path bindings/output \
        --subpkg-path bindings/output/packages \
        --log-level info
    
    if [ $? -eq 0 ]; then
        echo "✅ GTK 4 綁定生成成功！"
        echo "綁定文件位於：bindings/output/"
    else
        echo "❌ GTK 4 綁定生成失敗"
        echo "請檢查錯誤信息並手動調試"
    fi
else
    echo "❌ 無法運行 gidgen"
    echo "請檢查 gidgen 安裝"
fi

echo ""
echo "下一步："
echo "1. 如果綁定生成成功，更新 dub_gtk4.sdl 以使用新綁定"
echo "2. 修改 source/app_gtk4.d 以使用正確的 GTK 4 API"
echo "3. 編譯並測試：dub build -c dub_gtk4.sdl --config=gtk4"
